# 用于构建和测试 Java Maven 项目的工作流
# 包含依赖缓存以提高执行速度

name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  # 定时构建，确保项目持续可构建
  schedule:
    - cron: '0 2 * * 1' # 每周一凌晨2点运行
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
      fail-fast: false
    name: Java ${{ matrix.java }} 构建
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 设置 JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    
    - name: Maven 构建与验证
      run: ./mvnw clean verify -B -DprocessAllModules=true
    
    - name: 静态代码分析
      if: matrix.java == '17'
      run: ./mvnw spotbugs:check pmd:check checkstyle:check -B
    
    - name: 上传测试结果
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-java-${{ matrix.java }}
        path: '**/target/surefire-reports/*.xml'
        retention-days: 7
    
    - name: 上传代码覆盖率报告
      if: success() && matrix.java == '17'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: '**/target/site/jacoco/'
        retention-days: 7

  dependency-check:
    runs-on: ubuntu-latest
    name: 依赖安全检查
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置 JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: OWASP 依赖检查
      run: ./mvnw org.owasp:dependency-check-maven:check -B
    
    - name: 上传依赖检查报告
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: '**/target/dependency-check-report.html'
        retention-days: 7
