# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # 添加定时构建，确保项目持续可构建
  schedule:
    - cron: '0 2 * * 1' # 每周一凌晨2点运行

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.java }} build
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: ./mvnw clean verify -B -DprocessAllModules=true
      
    - name: Run tests with coverage
      run: ./mvnw test jacoco:report -B
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-java-${{ matrix.java }}
        path: '**/target/surefire-reports/*.xml'
        
    - name: Upload coverage report
      if: success() && matrix.java == '11'
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: '**/target/site/jacoco/'
